name: Check pre-commit-hooks.yaml
on:
  push:
    branches:
    - main

  pull_request:
    paths:
    - src/*
    - pyproject.toml
    - uv.lock
    - .pre-commit-hooks.yaml
    - .github/workflows/ci.yml

  schedule:
  # On day-of-month 15 at 3 am UTC
  - cron: 0 3 15 * *

  workflow_dispatch:

concurrency:
  # auto-cancel any in-progress job *on the same branch*
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  checks:
    name: py${{ matrix.interpreter.pyver }} VS pre-commit ${{ matrix.pre-commit-version }} VS ${{ matrix.downstream }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        interpreter:
        # the free-threading field is unused for stable versions but left for consistency
        - {pyver: 3.11.0, free-threading: false}
        - {pyver: 3.12, free-threading: false}
        - {pyver: 3.13, free-threading: false}
        - {pyver: 3.14, free-threading: false}
        - {pyver: 3.14t, free-threading: true}
        - {pyver: 3.15-dev, free-threading: false}
        - {pyver: 3.15-dev, free-threading: true}
        - {pyver: 3.16-dev, free-threading: false}
        - {pyver: 3.16-dev, free-threading: true}
        pre-commit-version:
        - 3.8.0
        - latest
        downstream:
        - idefix-code/idefix
        - la-niche/nonos
        - neutrinoceros/yt_idefix

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        path: main
        persist-credentials: false
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        path: downstream
        repository: ${{ matrix.downstream }}
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      if: "!endsWith(matrix.interpreter.pyver, '-dev')"
      with:
        python-version: ${{ matrix.interpreter.pyver }}
    - uses: deadsnakes/action@e640ac8743173a67cca4d7d77cd837e514bf98e8 # v3.2.0
      if: endsWith(matrix.python-version, '-dev')
      with:
        python-version: ${{ matrix.interpreter.pyver }}
        debug: true
        nogil: matrix.interpreter.free-threading
    - if: ${{ matrix.pre-commit-version == 'latest' }}
      run: pipx install pre-commit
    - if: ${{ matrix.pre-commit-version != 'latest' }}
      run: pipx install pre-commit==${{ matrix.pre-commit-version }}
    - name: Run pre-commit hooks
      shell: bash
      run: |
        cd downstream
        pre-commit try-repo ../main \
          --all-files --show-diff-on-failure
