name: Check pre-commit-hooks.yaml
on:
  push:
    branches:
    - main

  pull_request:
    paths:
    - src/*
    - pyproject.toml
    - uv.lock
    - .pre-commit-hooks.yaml
    - .github/workflows/ci.yml

  schedule:
  # On day-of-month 15 at 3 am UTC
  - cron: 0 3 15 * *

  workflow_dispatch:

concurrency:
  # auto-cancel any in-progress job *on the same branch*
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  checks:
    name: py${{ matrix.python-version }} VS pre-commit ${{ matrix.pre-commit-version }} VS ${{ matrix.downstream }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - 3.11.0
        - '3.14'
        - '3.15'
        pre-commit-version:
        - 3.8.0
        - latest
        downstream:
        - idefix-code/idefix
        - la-niche/nonos
        - neutrinoceros/yt_idefix

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        path: main
        persist-credentials: false
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd   # v6.0.2
      with:
        path: downstream
        repository: ${{ matrix.downstream }}
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      # 3.11.0 isn't available through setup-uv
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867   # v7.1.6
      with:
        enable-cache: false
    - name: Run pre-commit hooks
      run: |
        cd downstream
        uvx pre-commit@${{ matrix.pre-commit-version }} try-repo ../main \
          --all-files --show-diff-on-failure
